### ISSUE TITLE
411 

### ISSUE THREAD

**Issue by shaburov** [codepine/testrail-api-java-client#11]
```
TestRail testRail = TestRail
                .builder("<host>", "<login>", "<pass>")
                .applicationName("Test")
                .build();
testRail.runs().delete(15).execute();
```

Covert exception:
`Caused by: java.io.IOException: Server returned HTTP response code: 411 for URL: http://<host>/index.php?/api/v2/delete_run/15`

Log: 2016-06-13 03:33:43 DEBUG Request:145 - Response Code : 411

Pull request: https://github.com/codepine/testrail-api-java-client/pull/10

```
2016-06-13 03:48:48 DEBUG Request:146 - Response Code : 411

java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.BufferedInputStream@1b68ddbd; line: 1, column: 2]

    at com.codepine.api.testrail.Request.execute(Request.java:186)
    at com.codepine.api.testrail.internal.temp.asdasdasd(temp.java:17)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.BufferedInputStream@1b68ddbd; line: 1, column: 2]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2343)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:818)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:698)
    at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:1347)
    at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1253)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:865)
    at com.codepine.api.testrail.Request.execute(Request.java:154)
    ... 27 more
```

**Comment by kunal546** [comment]
Hi, I am unable to repro this issue. Which TestRail version are you using?

**Comment by OlegusTesterovichus** [comment]
Hi, I am using TestRail v 5.2.1.3472 (last version).

**Comment by pavetok** [comment]
+1

**Comment by pavetok** [comment]
When I try to close:
        testRailApi.runs()
                .close(testRailRun.getId())
                .execute();
