### ISSUE TITLE
Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token for "config" property

### ISSUE THREAD

**Issue by Kate5** [codepine/testrail-api-java-client#15]
Hi everyone!
I receive following error 
```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
 at [Source: java.io.BufferedInputStream@2002348; line: 1, column: 161] (through reference chain: com.codepine.api.testrail.model.Run["config"])
```

when execute request for loading test run
`testRail.runs().get(some_id).execute()`

This error appears when server response contains not null config property
`"config":"some_value"`
Could you help please?

**Comment by gogonutsss** [comment]
I do receive a similar runtime exception when I send testRail.plans().get(planId).execute() for a test plan that has run(s) inside as a result of usage of Groups/Configuration feature of TestRail.

Any plan to fix this or any workaround idea?

>  com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token at [Source: java.io.BufferedInputStream@87a85e1; line: 1, column: 2901] (through reference chain: com.codepine.api.testrail.model.Plan["entries"]->com.codepine.api.testrail.model.Entry["runs"]->com.codepine.api.testrail.model.Run["config"])

**Comment by hugomcconnell** [comment]
Hi,

I'm experiencing he same issue - is there a plan to fix this?

**Comment by gulwaniv** [comment]
I am facing same issue, please fix.

**Comment by GuiMiran** [comment]
hi i have same Issue, i hope this solution. Thnaks !

java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
 at [Source: java.io.BufferedInputStream@4034c28c; line: 1, column: 1217] (through reference chain: com.codepine.api.testrail.model.Plan["entries"]->com.codepine.api.testrail.model.Entry["runs"]->com.codepine.api.testrail.model.Run["config"])
	at com.codepine.api.testrail.Request.execute(Request.java:172)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
 at [Source: java.io.BufferedInputStream@4034c28c; line: 1, column: 1217] (through reference chain: com.codepine.api.testrail.model.Plan["entries"]->com.codepine.api.testrail.model.Entry["runs"]->com.codepine.api.testrail.model.Run["config"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:691)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:685)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:154)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:19)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.codepine.api.testrail.internal.PlanModule$PlanDeserializer.deserialize(PlanModule.java:63)
	at com.codepine.api.testrail.internal.PlanModule$PlanDeserializer.deserialize(PlanModule.java:52)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2144)
	at com.codepine.api.testrail.Request.execute(Request.java:154)
	... 30 more

**Comment by michaelmendoza42** [comment]
same issue here. i see a PR with a potential fix. can we get that reviewed/merged?
