### ISSUE TITLE
ignore unknown custom fields

### ISSUE THREAD

**Issue by alexeyOnGitHub** [codepine/testrail-api-java-client#5]
this is kinda related to Issue #2 .

I'm looking for a workaround that would eliminate the need to load custom fields from server (which results in NPE):

```
//        final List<CaseField> customCaseFields = client.caseFields().list().execute();
```

so I tried this:

```
    final CaseField field = (CaseField) new CaseField().setName("automated_test_name");
    return client.cases().list(projectId, suiteId, Arrays.asList(field)).execute();
```

but I get:

```
java.lang.IllegalArgumentException: Case field list configuration is possibly outdated since it does not contain custom field: preconds
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
at com.codepine.api.testrail.internal.CaseModule$CaseDeserializer.deserialize(CaseModule.java:87)
at com.codepine.api.testrail.internal.CaseModule$CaseDeserializer.deserialize(CaseModule.java:65)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1270)
at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:865)
at com.codepine.api.testrail.Request.execute(Request.java:162)
at org.jenkinsci.plugin.trp.TestRailClient.getCases(TestRailClient.java:156)
```

so, if I only care about 1 particular custom field for these results, I would expect the API to not fail for any other custom fields I don't know / don't care about.

also, in a more common scenario, there could be some custom fields added on the server in the time period between custom fields are loaded by a client and cases are loaded by the same client.
if the client does not care about newly added fields, then I think the API should not fail.

**Comment by kunal546** [comment]
Also related to issue #3 which translates to "ignore all custom fields".

There could also be a scenario where the type of the custom field changes on server side due to which the API fails. In this case, it would be good to fail-fast due to "outdated" field list.

But in general, I agree with the idea of not making custom fields a requirement.

Currently, once you have an instance of Case, there is a guarantee that Case#getCustomFields returns an instance with correct implementation type. The new requirement of "not having required custom fields" sort of breaks Case#getCustomField API since its success is now dependent on whether the requested custom field was known to the client (and correct) or not. This was one of the reasons for making it a requirement.
