### ISSUE TITLE
How to add test run into test plan?

### ISSUE THREAD

**Issue by Zeloslaw** [codepine/testrail-api-java-client#65]
Hello,
I have a problem, 
I don't know how to add test run into test plan.
I tried the solution found on the internet:
`TestRail testRail = TestRail.builder(ConfigProperties.getTestRailUrl(), ConfigProperties.getTestRailUser(), ConfigProperties.getTestRailPassword()).build();
        Plan.Entry.Run run = new Plan.Entry.Run();
        run.setName("AQA test");
        Plan.Entry entry = new Plan.Entry().setRuns(Arrays.asList(run));
        entry.setSuiteId(566469);
        Plan.Entry plan = testRail.plans().addEntry(16, entry).execute();`
        
Unfortunately, I get an error message:
`com.codepine.api.testrail.TestRailException: 403 - You are not allowed to edit test plans (insufficient permissions).
        at com.codepine.api.testrail.TestRailException$Builder.build(TestRailException.java:57)
        at com.codepine.api.testrail.Request.execute(Request.java:142)
        at testrail.TestPlanLauncher.main(TestPlanLauncher.java:19)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by Zeloslaw** [comment]
it was my mistake, i used closed test plan id
