### ISSUE TITLE
TestRail API was changed - may you update it to the latest structure?

### ISSUE THREAD

**Issue by maksimsarychau** [codepine/testrail-api-java-client#67]
Hello.
TestRail release the new API everywhere last weekend. 
Changes are based on https://discuss.gurock.com/t/bulk-api-endpoint-changes-coming-soon/19537 
And now all parses from this library stop worked. :( 
I got errors like: 
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: (BufferedInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:691)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:685)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:214)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1270)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:865)
	at com.codepine.api.testrail.Request.execute(Request.java:164)

**Comment by cameroncooks-branch** [comment]
+1 same issue here. If anyone creates a patch for this it would be greatly appreciated

**Comment by SaintDuriel** [comment]
Seconded, Unable to parse any responses from Test Rail with the latest update to their API.

**Comment by kbilokura** [comment]
+1 same issue here

**Comment by maksimsarychau** [comment]
@kunal546 @apolaskey @ChenChiaHung as contributors - may you take a look?

**Comment by pwebster-cpi** [comment]
+1
For example, the `get_cases` endpoint now returns JSON like this:
```
{
    "offset": 0,
    "limit": 250,
    "size": 129,
    "_links": {
        "next": null,
        "prev": null
    },
    "cases": [
        {...
```
So the root node is not an `instanceof ArrayNode` and so can't be deserialized into a `List`? (I'm just guessing.)

**Comment by maksimsarychau** [comment]
@pwebster-cpi yep. But not only for get_cases. 
Following have to be updated as well. 
get_cases
get_runs
get_results
get_tests
get_results_for_case
get_results_for_run
get_plans
get_projects
get_sections
get_milestones
get_history_for_case
get_attachments_for_case
get_attachments_for_run
Get_attachments_for_plan

But in some cases the old List is still actual.

**Comment by kbilokura** [comment]
Hi @maksimsarychau, I'm just interesting if you are going to use another library for testrail integration or wait for the fix?

**Comment by maksimsarychau** [comment]
Hi @kbilokura, I didn't find any up-to-date and with such wide functionality :( If you find something - please let me know. I'm really waiting for a fix but in parallel trying to add direct API calls in my code as a workaround (without this library)

**Comment by pwebster-cpi** [comment]
I just saw this fork with changes made yesterday:
https://github.com/pablo-iglesias/testrail-api-java-client

I have not yet looked closely at it, but there is a new file named "PageDeserializer.java". Sounds promising...

**Comment by maksimsarychau** [comment]
Thank you @pwebster-cpi 
Just checked - it works for me with get_plans, get_projects, get_sections
But for other calls like List of get_cases or get_results showing the same error. 
May you check as well? 
Maybe I missed something in the updated syntax.

**Comment by cameroncooks-branch** [comment]
The https://github.com/pablo-iglesias/testrail-api-java-client fork worked for me, with a small bug fix re: _next URL's in the Request.java execute() method

**Comment by maksimsarychau** [comment]
@pwebster-cpi Did you have a chance to check? 
I found that solution from @pablo-iglesias works only for totally standard Testrail objects. 
But if there is any custom field in any of the required List - there is a problem with parsing. 
Logic with a bug starts from this line: 
https://github.com/pablo-iglesias/testrail-api-java-client/blob/39d5e7d78f768220ccacdb16202115900d08899c/src/main/java/com/codepine/api/testrail/Request.java#L208

**Comment by maksimsarychau** [comment]
> The https://github.com/pablo-iglesias/testrail-api-java-client fork worked for me, with a small bug fix re: _next URL's in the Request.java execute() method
@cameroncooks-branch 
May you share your fix? 
Did you try to process with any custom fields in get_cases or get_results ?

**Comment by cameroncooks-branch** [comment]
> > The https://github.com/pablo-iglesias/testrail-api-java-client fork worked for me, with a small bug fix re: _next URL's in the Request.java execute() method
> > @cameroncooks-branch
> > May you share your fix?
> > Did you try to process with any custom fields in get_cases or get_results ?

I only needed the fix because my baseurl is https://www.demo.test/testing?/api/v2/
and the _next link was /api/v2/some/testrails/url

so when combined by getURL it would end up being https://www.demo.test/testing?/api/v2//api/v2/some/testrails/url

just a problem with not using an actual base baseurl

**Comment by pablo-iglesias** [comment]
Hey,
I have pushed a fix for both issues, custom fields, and strip api part from _next URL.
**Be adviced that I will erase this fork in a few days.**
Kind regards

**Comment by maksimsarychau** [comment]
Really big thanks @pablo-iglesias. It works! 
Just one small problem with a test G_casesExists_W_getCasesWithFilter_T_verifyFilterQueryAndCases() during mvn install. 

Btw, where to I can order a coffee or cake (beer) for you? :)

**Comment by pablo-iglesias** [comment]
Lol, you are welcome.
Sorry, I forgot to add the json file, I've just pushed it.
Remember, I will erase the fork in a few days.

**Comment by maksimsarychau** [comment]
Thanks for your help!
One more fix and pull request is available there:
https://github.com/codepine/testrail-api-java-client/pull/68
Does anybody have permission to merge?

**Comment by kunal546** [comment]
Sorry for the delay. I have merged this and made a new release v2.0.2.

**Comment by eck-song** [comment]
Hi. 

I am having the same problem with the revised version 2.0.2.
```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: java.io.BufferedInputStream@5fd1b2ea; line: 1, column: 1]
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: java.io.BufferedInputStream@5fd1b2ea; line: 1, column: 1]
```

The code I use is as below.
`val milestone: MutableList<Milestone> = testrail.Milestones().list(4).execute()`

How should I use it?

@kunal546
