### ISSUE TITLE
java.lang.Class.getDeclaredFields0: Expecting a stackmap frame at branch target

### ISSUE THREAD

**Issue by alexeyOnGitHub** [codepine/testrail-api-java-client#7]
got this when using the library in a Jenkins plugin:

```
 java.lang.VerifyError: Expecting a stackmap frame at branch target 7
Exception Details:
  Location:
   com/codepine/api/testrail/model/Project.equals(Ljava/lang/Object;)Z @2: if_acmpne
  Reason:
  Expected stackmap frame at this location.
  Bytecode:
    0000000: 2b2a a600 0504 ac2b c100 029a 0005 03ac
at java.lang.Class.getDeclaredFields0(Native Method)
at java.lang.Class.privateGetDeclaredFields(Class.java:2499)
at java.lang.Class.getDeclaredFields(Class.java:1811)
at com.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:683)
at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveFields(AnnotatedClass.java:470)
at com.fasterxml.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:282)
at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:380)
at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collect(POJOPropertiesCollector.java:233)
at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:142)
at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(BasicClassIntrospector.java:81)
at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(BasicClassIntrospector.java:11)
at com.fasterxml.jackson.databind.DeserializationConfig.introspect(DeserializationConfig.java:547)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:325)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:263)
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:243)
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:144)
at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:366)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:150)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:23)
at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:572)
at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:386)
at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3095)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2989)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2151)
at com.codepine.api.testrail.Request.execute(Request.java:164)
at org.jenkinsci.plugin.trp.TestRailClient.getProjectId(TestRailClient.java:104)
at   org.jenkinsci.plugin.trp.BuildRunListener.processBuildCompletedNotification(BuildRunListener.java:60)
at org.jenkinsci.plugin.trp.BuildRunListener.onCompleted(BuildRunListener.java:39)
at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
at hudson.model.Run.execute(Run.java:1786)
at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:381)
```

**Comment by alexeyOnGitHub** [comment]
looks like it's a problem with my JDK. one of the servers was using OpenJDK 1.7 instead of Oracle JDK 1.7... I'll close this.

**Comment by alexeyOnGitHub** [comment]
interesting... still have the same problem. do you remember what JDK version did you use? the exact version, including Oracle/OpenJDK/etc.

It seems like the Jenkins plugin I'm working on can be compiled with this library, but then JVM fails to parse. so there is source/signature compatibility, but no binary compatibility.

**Comment by alexeyOnGitHub** [comment]
my current theory is that the problem is related to Lombok that you are using. 
I verified that if I comment our the library calls I don't get JVM failures in Jenkins.

**Comment by jpederzolli** [comment]
@alexeyOnGitHub this is actually a Jenkins bug (https://issues.jenkins-ci.org/browse/JENKINS-28781)

**Comment by kunal546** [comment]
Seems like it'a a Jenkins bug. Closing it. Please re-open if this is still an issue.
